version: '3.7'

services:
  web:
    build: .
    command:  >
      bash -c "
        python manage.py makemigrations &&
        python manage.py migrate &&
        (python manage.py create_default_login || true) &&
        (python manage.py create_default_participant || true) &&
        python app.py
      "
    volumes:
      - .:/code
    ports:
      - 8080:8080
    env_file:
      - ./.env.dev
    depends_on:
      - db
  lab:
    build: .
    command:  >
      bash -c "
        jupyter lab --ip=0.0.0.0 --no-browser --allow-root
      "
    volumes:
      - .:/code
    ports:
      - 8888:8888
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.dev

volumes:
  postgres_data: