# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-06 16:14
from django.db import migrations

from libs.security import generate_random_string, generate_hash_and_salt


def add_admin_user_if_not_exists(apps, schema_editor):
    Researcher = apps.get_model('database', 'Researcher')

    if Researcher.objects.count() == 0:
        access_key = generate_random_string()[:64]
        secret_key = generate_random_string()[:64]
        secret_hash, secret_salt = generate_hash_and_salt(secret_key)
        access_key_id = access_key
        access_key_secret = secret_hash
        access_key_secret_salt = secret_salt
        password, salt = generate_hash_and_salt(b"abc123")

        r = Researcher(
            username="default_admin",
            admin=True,
            password=password.decode(),
            salt=salt.decode(),
            access_key_id=access_key_id.decode(),
            access_key_secret=access_key_secret.decode(),
            access_key_secret_salt=access_key_secret_salt.decode(),
        )
        r.save()


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_study_is_test'),
    ]

    operations = [
        migrations.RunPython(add_admin_user_if_not_exists)
    ]
