# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-14 17:57
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0013_auto_20180530_0153'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicesettings',
            name='use_gps_fuzzing',
            field=models.BooleanField(default=False),
        ),
    ]
