# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-16 21:21
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0014_devicesettings_use_gps_fuzzing'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipantFieldValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='StudyField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.TextField()),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fields', to='database.Study')),
            ],
        ),
        migrations.AddField(
            model_name='participantfieldvalue',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_values', to='database.StudyField'),
        ),
        migrations.AddField(
            model_name='participantfieldvalue',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='field_values', to='database.Participant'),
        ),
        migrations.AlterUniqueTogether(
            name='studyfield',
            unique_together=set([('study', 'field_name')]),
        ),
        migrations.AlterUniqueTogether(
            name='participantfieldvalue',
            unique_together=set([('participant', 'field')]),
        ),
    ]
