# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-10 17:57
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0015_auto_20181116_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicesettings',
            name='call_clinician_button_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='devicesettings',
            name='call_research_assistant_button_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
