# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-06-13 19:43
import database.common_models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0017_chunkregistry_file_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardColorSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('data_type', models.CharField(max_length=32)),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dashboard_colors', to='database.Study')),
            ],
        ),
        migrations.CreateModel(
            name='DashboardGradient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('color_range_min', models.IntegerField(default=0)),
                ('color_range_max', models.IntegerField(default=0)),
                ('dashboard_color_setting', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='gradient', to='database.DashboardColorSetting')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DashboardInflection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('operator', models.CharField(max_length=1)),
                ('inflection_point', models.IntegerField(default=0)),
                ('dashboard_color_setting', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inflections', to='database.DashboardColorSetting')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterUniqueTogether(
            name='dashboardcolorsetting',
            unique_together=set([('data_type', 'study')]),
        ),
    ]
