# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-06-17 20:50
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0018_auto_20190611_2127'),
        ('database', '0018_auto_20190613_1943'),
    ]

    operations = [
    ]
