# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-06-18 18:58
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0019_merge_20190617_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipelineregistry',
            name='data_type',
            field=models.CharField(db_index=True, max_length=256),
        ),
    ]
