# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-07-16 00:57
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0020_auto_20190618_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chunkregistry',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
