# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-03 19:28
from __future__ import unicode_literals

import database.common_models
import django.core.validators
from django.db import migrations, models

from database.user_models import Researcher


def convert_batch_users(apps, schema_editor):
    for researcher in Researcher.objects.all():
        if researcher.username.startswith("BATCH USER"):
            researcher.is_batch_user = True
            researcher.save()

class Migration(migrations.Migration):

    dependencies = [
        ('database', '0022_auto_20190827_0011'),
    ]

    operations = [
        migrations.AddField(
            model_name='researcher',
            name='is_batch_user',
            field=models.BooleanField(default=False),
        ),
        # custom
        migrations.RunPython(convert_batch_users),

        migrations.AlterField(
            model_name='devicesettings',
            name='about_page_text',
            field=models.TextField(default="The Beiwe application runs on your phone and helps researchers collect information about your behaviors. Beiwe may ask you to fill out short surveys or to record your voice. It may collect information about your location (using phone GPS) and how much you move (using phone accelerometer). Beiwe may also monitor how much you use your phone for calling and texting and keep track of the people you communicate with. Importantly, Beiwe never records the names or phone numbers of anyone you communicate with. While it can tell if you call the same person more than once, it does not know who that person is. Beiwe also does not record the content of your text messages or phone calls. Beiwe may keep track of the different Wi-Fi networks and Bluetooth devices around your phone, but the names of those networks are replaced with random codes.\n\nAlthough Beiwe collects large amounts of data, the data is processed to protect your privacy. This means that it does not know your name, your phone number, or anything else that could identify you. Beiwe only knows you by an identification number. Because Beiwe does not know who you are, it cannot communicate with your clinician if you are ill or in danger. Researchers will not review the data Beiwe collects until the end of the study. To make it easier for you to connect with your clinician, the 'Call my Clinician' button appears at the bottom of every page.\n\nBeiwe was conceived and designed by Dr. Jukka-Pekka 'JP' Onnela at the Harvard T.H. Chan School of Public Health. Development of the Beiwe smartphone application and data analysis software is funded by NIH grant 1DP2MH103909-01 to Dr. Onnela. The smartphone application was built by Zagaran, Inc., in Cambridge, Massachusetts."),
        ),
        migrations.AlterField(
            model_name='devicesettings',
            name='consent_form_text',
            field=models.TextField(default='I have read and understood the information about the study and all of my questions about the study have been answered by the study researchers.'),
        ),
        migrations.AlterField(
            model_name='devicesettings',
            name='consent_sections',
            field=database.common_models.JSONTextField(default='{"welcome": {"text": "", "more": ""}, "data_gathering": {"text": "", "more": ""}, "privacy": {"text": "", "more": ""}, "data_use": {"text": "", "more": ""}, "time_commitment": {"text": "", "more": ""}, "study_survey": {"text": "", "more": ""}, "study_tasks": {"text": "", "more": ""}, "withdrawing": {"text": "", "more": ""}}'),
        ),
        migrations.AlterField(
            model_name='devicesettings',
            name='survey_submit_success_toast_text',
            field=models.TextField(default="Thank you for completing the survey. A clinician will not see your answers immediately, so if you need help or are thinking about harming yourself, please contact your clinician. You can also press the 'Call My Clinician' button."),
        ),
        migrations.AlterField(
            model_name='lineencryptionerror',
            name='type',
            field=models.CharField(choices=[('AES_KEY_BAD_LENGTH', 'AES_KEY_BAD_LENGTH'), ('EMPTY_KEY', 'EMPTY_KEY'), ('INVALID_LENGTH', 'INVALID_LENGTH'), ('IV_BAD_LENGTH', 'IV_BAD_LENGTH'), ('IV_MISSING', 'IV_MISSING'), ('LINE_EMPTY', 'LINE_EMPTY'), ('LINE_IS_NONE', 'LINE_IS_NONE'), ('MP4_PADDING', 'MP4_PADDING'), ('MALFORMED_CONFIG', 'MALFORMED_CONFIG'), ('PADDING_ERROR', 'PADDING_ERROR')], max_length=32),
        ),
        migrations.AlterField(
            model_name='participant',
            name='password',
            field=models.CharField(help_text="A hash of the user's password", max_length=44, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z_\\-]+={0,2}$')]),
        ),
        migrations.AlterField(
            model_name='participant',
            name='patient_id',
            field=models.CharField(help_text='Eight-character unique ID with characters chosen from 1-9 and a-z', max_length=8, unique=True, validators=[django.core.validators.RegexValidator('^[1-9a-z]+$', message='This field can only contain characters 1-9 and a-z.')]),
        ),
        migrations.AlterField(
            model_name='participant',
            name='salt',
            field=models.CharField(max_length=24, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z_\\-]+={0,2}$')]),
        ),
        migrations.AlterField(
            model_name='researcher',
            name='access_key_id',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z+/]+={0,2}$')]),
        ),
        migrations.AlterField(
            model_name='researcher',
            name='access_key_secret',
            field=models.CharField(blank=True, max_length=44, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z_\\-]+={0,2}$')]),
        ),
        migrations.AlterField(
            model_name='researcher',
            name='access_key_secret_salt',
            field=models.CharField(blank=True, max_length=24, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z_\\-]+={0,2}$')]),
        ),
        migrations.AlterField(
            model_name='researcher',
            name='password',
            field=models.CharField(help_text="A hash of the user's password", max_length=44, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z_\\-]+={0,2}$')]),
        ),
        migrations.AlterField(
            model_name='researcher',
            name='salt',
            field=models.CharField(max_length=24, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z_\\-]+={0,2}$')]),
        ),
        migrations.AlterField(
            model_name='survey',
            name='timings',
            field=database.common_models.JSONTextField(default='[[], [], [], [], [], [], []]', help_text='JSON blob containing the times at which the survey is sent.'),
        ),
        migrations.AlterField(
            model_name='surveyarchive',
            name='timings',
            field=database.common_models.JSONTextField(default='[[], [], [], [], [], [], []]', help_text='JSON blob containing the times at which the survey is sent.'),
        ),
    ]
