# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-02-21 20:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0024_custom'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyEvents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField()),
                ('event_type', models.CharField(choices=[('notified', 'notified'), ('expired', 'expired'), ('completed', 'completed')], help_text='What type of event is being recorded.', max_length=16)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='survey_events', to='database.Participant')),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='survey_events', to='database.Study')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='database.Survey')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
