# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-01-06 21:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0024_custom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chunkregistry',
            name='chunk_path',
            field=models.CharField(db_index=True, max_length=256, unique=True),
        ),
    ]
