# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-02-21 23:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0025_surveyevents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyevents',
            name='event_type',
            field=models.CharField(choices=[('notified', 'notified'), ('expired', 'expired'), ('submitted', 'submitted')], help_text='What type of event is being recorded.', max_length=16),
        ),
        migrations.AlterUniqueTogether(
            name='surveyevents',
            unique_together=set([('study', 'survey', 'participant', 'timestamp', 'event_type')]),
        ),
    ]
