# Generated by Django 2.2.10 on 2020-03-04 20:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0025_auto_20200106_2153'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intervention',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='participant',
            name='fcm_instance_id',
            field=models.CharField(blank=True, db_index=True, help_text='The id used to send push notifications to the device.', max_length=256),
        ),
        migrations.AddField(
            model_name='study',
            name='timezone',
            field=models.CharField(blank=True, help_text='Timezone of the study', max_length=64),
        ),
        migrations.AddField(
            model_name='survey',
            name='schedule_type',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='participantfieldvalue',
            name='value',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='pipelineupload',
            name='study',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pipeline_uploads', to='database.Study'),
        ),
        migrations.AlterField(
            model_name='studyrelation',
            name='researcher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_relations', to='database.Researcher'),
        ),
        migrations.AlterField(
            model_name='studyrelation',
            name='study',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_relations', to='database.Study'),
        ),
        migrations.CreateModel(
            name='WeeklySchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('day_of_week', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(6)])),
                ('hour', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(23)])),
                ('minute', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(59)])),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='weekly_schedules', to='database.Survey')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RelativeSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('days_after', models.IntegerField(default=0)),
                ('hour', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(23)])),
                ('minute', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(59)])),
                ('intervention', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='relative_schedules', to='database.Intervention')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='relative_schedules', to='database.Participant')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='relative_schedules', to='database.Survey')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='intervention',
            name='study',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='interventions', to='database.Study'),
        ),
        migrations.CreateModel(
            name='ArchivedEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('schedule_type', models.CharField(max_length=32)),
                ('scheduled_time', models.DateTimeField()),
                ('response_time', models.DateTimeField(null=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='archived_events', to='database.Participant')),
                ('survey_archive', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='archived_events', to='database.SurveyArchive')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AbsoluteSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('scheduled_date', models.DateTimeField()),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='absolute_schedules', to='database.Survey')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ScheduledEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('scheduled_time', models.DateTimeField()),
                ('absolute_schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_events', to='database.AbsoluteSchedule')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scheduled_events', to='database.Participant')),
                ('relative_schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_events', to='database.RelativeSchedule')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scheduled_events', to='database.Survey')),
                ('weekly_schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_events', to='database.WeeklySchedule')),
            ],
            options={
                'unique_together': {('survey', 'participant', 'scheduled_time')},
            },
        ),
        migrations.CreateModel(
            name='InterventionDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('intervention', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intervention_dates', to='database.Intervention')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intervention_dates', to='database.Participant')),
            ],
            options={
                'unique_together': {('participant', 'intervention')},
            },
        ),
    ]
