# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-04-08 22:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0026_auto_20200221_2344'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoxIntegration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('access_token', models.CharField(max_length=256)),
                ('refresh_token', models.CharField(max_length=256)),
                ('write_to_directory', models.CharField(max_length=256)),
                ('researcher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='box_integration', to='database.Researcher', unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
