# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-04 22:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0026_custom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='schedule_type',
            field=models.CharField(default='weekly', max_length=32, null=True),
        ),
    ]
