# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-04-08 22:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0027_boxintegration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boxintegration',
            name='id',
        ),
        migrations.AlterField(
            model_name='boxintegration',
            name='researcher',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='box_integration', serialize=False, to='database.Researcher'),
        ),
    ]
