# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-04-09 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0028_auto_20200408_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boxintegration',
            name='write_to_directory',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
