# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-05 20:15
from __future__ import unicode_literals

from django.db import migrations

from database.survey_models import Survey


def fix_bad_survey_content(*args, **kwargs):
    Survey.objects.filter(content="null").update(content="[]")

class Migration(migrations.Migration):

    dependencies = [
        ('database', '0028_auto_20200305_2015'),
    ]

    operations = [
        migrations.RunPython(fix_bad_survey_content)

    ]
