# Generated by Django 2.2.11 on 2020-03-10 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0029_manual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absoluteschedule',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absolute_schedules', to='database.Survey'),
        ),
        migrations.AlterField(
            model_name='relativeschedule',
            name='intervention',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relative_schedules', to='database.Intervention'),
        ),
        migrations.AlterField(
            model_name='relativeschedule',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relative_schedules', to='database.Survey'),
        ),
        migrations.AlterField(
            model_name='scheduledevent',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_events', to='database.Survey'),
        ),
        migrations.AlterField(
            model_name='weeklyschedule',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_schedules', to='database.Survey'),
        ),
    ]
