# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-04-17 04:07
from __future__ import unicode_literals

import database.common_models
import database.validators
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0029_auto_20200409_1506'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipantSurvey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('name', models.TextField(help_text='Name of the study; can be of any length', null=True, unique=True)),
                ('content', database.common_models.JSONTextField(default='[]', help_text='JSON blob containing information about the survey questions.')),
                ('survey_type', models.CharField(choices=[('audio_survey', 'audio_survey'), ('tracking_survey', 'tracking_survey'), ('dummy', 'dummy'), ('image_survey', 'image_survey')], help_text='What type of survey this is.', max_length=16)),
                ('settings', database.common_models.JSONTextField(default='{}', help_text='JSON blob containing settings for the survey.')),
                ('timings', database.common_models.JSONTextField(default='[[], [], [], [], [], [], []]', help_text='JSON blob containing the times at which the survey is sent.')),
                ('object_id', models.CharField(max_length=24, unique=True, validators=[database.validators.LengthValidator(24)])),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participant_surveys', to='database.Participant')),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participant_surveys', to='database.Study')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StudyConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('study_configuration', django.contrib.postgres.fields.jsonb.JSONField()),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='database.Study')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='survey',
            name='name',
            field=models.TextField(help_text='Name of the study; can be of any length', null=True, unique=True),
        ),
        migrations.AddField(
            model_name='surveyarchive',
            name='name',
            field=models.TextField(help_text='Name of the study; can be of any length', null=True, unique=True),
        ),
    ]
