# Generated by Django 2.2.11 on 2020-03-10 17:41

from django.db import migrations
import timezone_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0030_auto_20200310_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='timezone',
            field=timezone_field.fields.TimeZoneField(default='America/New_York', help_text='Timezone of the study'),
        ),
    ]
