# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-04-17 04:07
from __future__ import unicode_literals

from django.db import migrations

def survey_names(apps, schema_editor):

    Survey = apps.get_model('database', 'Survey')
    for survey in Survey.objects.all():
        survey.name = "Study survey {}".format(survey.object_id)
        survey.save()

    SurveyArchive = apps.get_model('database', 'SurveyArchive')
    for survey in SurveyArchive.objects.all():
        survey.name = "Archived study survey {} {}".format(survey.survey.object_id, survey.archive_end.isoformat())
        survey.save()

    ParticipantSurvey = apps.get_model('database', 'ParticipantSurvey')
    for survey in ParticipantSurvey.objects.all():
        survey.name = "Participant survey {}".format(survey.object_id)
        survey.save()


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0030_auto_20200417_0407'),
    ]

    operations = [
        migrations.RunPython(survey_names),
    ]
