# Generated by Django 2.2.11 on 2020-03-10 17:41

from django.db import migrations

# this is a dummy migration.  Due to a schema change the location of this script moved to
# database/migrations/0035_auto_20200518_1908.py

def backfill_missing_survey_archives(*args, **kwargs):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('database', '0031_auto_20200310_1741'),
    ]

    operations = [
        migrations.RunPython(backfill_missing_survey_archives, reverse_code=migrations.RunPython.noop),
    ]
