# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-04-17 04:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0031_fix_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participantsurvey',
            name='name',
            field=models.TextField(help_text='Name of the study; can be of any length', unique=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='name',
            field=models.TextField(help_text='Name of the study; can be of any length', unique=True),
        ),
        migrations.AlterField(
            model_name='surveyarchive',
            name='name',
            field=models.TextField(help_text='Name of the study; can be of any length', unique=True),
        ),
    ]
