# Generated by Django 2.2.11 on 2020-03-10 17:41

from django.db import migrations

from database.survey_models import Survey


def backfill_missing_survey_archives(*args, **kwargs):
    """ We need to fill SurveyArchive objects for all surveys predating its existence. """
    for survey in Survey.objects.filter(archives__isnull=True):
        # SurveyArchives are defined in the save trigger.
        survey.save()


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0031_auto_20200310_1741'),
    ]

    operations = [
        migrations.RunPython(backfill_missing_survey_archives, reverse_code=migrations.RunPython.noop),
    ]
