# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-04-17 04:39
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0032_auto_20200417_0415'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipantAliases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('reference_id', models.CharField(help_text='Eight-character unique ID with characters chosen from 1-9 and a-z', max_length=8, validators=[django.core.validators.RegexValidator('^[1-9a-z]+$', message='This field can only contain characters 1-9 and a-z.')])),
                ('alias_id', models.CharField(help_text='Eight-character unique ID with characters chosen from 1-9 and a-z', max_length=8, validators=[django.core.validators.RegexValidator('^[1-9a-z]+$', message='This field can only contain characters 1-9 and a-z.')])),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participant_aliases', to='database.Study')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
