# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-04-17 04:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0033_participantaliases'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participantsurvey',
            name='name',
            field=models.TextField(help_text='Name of the study; can be of any length'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='name',
            field=models.TextField(help_text='Name of the study; can be of any length'),
        ),
        migrations.AlterField(
            model_name='surveyarchive',
            name='name',
            field=models.TextField(help_text='Name of the study; can be of any length'),
        ),
        migrations.AlterUniqueTogether(
            name='survey',
            unique_together=set([('study', 'name')]),
        ),
    ]
