# Generated by Django 2.2.11 on 2020-05-18 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0034_auto_20200506_2212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveyarchive',
            name='archive_end',
        ),
        migrations.RemoveField(
            model_name='surveyarchive',
            name='study',
        ),
    ]
