# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-04-17 08:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0035_pipelineexecutiontracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipelineexecutiontracking',
            name='box_directory',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='pipelineexecutiontracking',
            name='job_type',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
