# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-04-21 19:12
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0036_auto_20200417_0848'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipelineexecutiontracking',
            name='datastreams',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pipelineexecutiontracking',
            name='json_participants',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
