# Generated by Django 2.2.14 on 2020-07-29 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0036_auto_20200624_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participantfcmhistory',
            name='unregistered',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
