# Generated by Django 2.2.11 on 2020-07-09 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0037_summarystatisticdaily'),
    ]

    operations = [
        migrations.RenameField(
            model_name='summarystatisticdaily',
            old_name='significant_location_entroy',
            new_name='significant_location_entropy',
        ),
    ]
