# Generated by Django 2.2.11 on 2020-07-07 01:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0037_schematableauapi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schematableauapi',
            name='participant_id',
        ),
        migrations.RemoveField(
            model_name='schematableauapi',
            name='study_id',
        ),
        migrations.AddField(
            model_name='schematableauapi',
            name='participant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='database.Participant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schematableauapi',
            name='study',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='database.Study'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='schematableauapi',
            name='acceleration_direction',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='schematableauapi',
            name='accelerometer_coverage_fraction',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='schematableauapi',
            name='accelerometer_signal_variability',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='schematableauapi',
            name='awake_onset_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='schematableauapi',
            name='sleep_onset_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='schematableauapi',
            name='stationary_fraction',
            field=models.TextField(),
        ),
    ]
