# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-04-21 19:13
from __future__ import unicode_literals

from django.db import migrations
from database.pipeline_models import PipelineExecutionTracking
import json

class Migration(migrations.Migration):

    def forward_data_migration(apps, schema):
        for pipeline in PipelineExecutionTracking.objects.all():
            try:
                participants=pipeline.participants
                if ',' in participants:
                    participants=[pt for pt in participants.split(',') if pt]
                if ' ' in participants:
                    participants=[pt for pt in participants.split(' ') if pt]
                if not isinstance(participants, list):
                    participants = list(participants)

                pipeline.json_participants = json.dumps(participants)
            except json.decoder.JSONDecodeError as e:
                print(f'Cannot convert {pipeline.pk} object')

    def revert_migration(apps, schema):
        pass

    dependencies = [
        ('database', '0037_auto_20200421_1912'),
    ]

    operations = [
        migrations.RunPython(
            code=forward_data_migration,
            reverse_code=revert_migration
        )
    ]
