# Generated by Django 2.2.14 on 2020-07-30 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0037_auto_20200729_0715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivedevent',
            name='response_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
