# Generated by Django 2.2.11 on 2020-07-29 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0038_summarystatisticdaily'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='readable_name',
            field=models.TextField(blank=True, default=''),
        ),
    ]
