# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-04-21 19:21
from __future__ import unicode_literals

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('database', '0038_auto_20200421_1913'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pipelineexecutiontracking',
            old_name='participants',
            new_name='old_participants'
        ),
        migrations.RenameField(
            model_name='pipelineexecutiontracking',
            old_name='json_participants',
            new_name='participants'
        )

    ]
