# Generated by Django 2.2.14 on 2020-08-19 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0038_auto_20200730_0413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivedevent',
            name='response_time',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='archivedevent',
            name='schedule_type',
            field=models.CharField(db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='archivedevent',
            name='scheduled_time',
            field=models.DateTimeField(db_index=True),
        ),
    ]
