# Generated by Django 2.2.11 on 2020-09-29 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0039_auto_20200819_1901'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileAsText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('tag', models.CharField(db_index=True, max_length=256)),
                ('text', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
