# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-04-21 19:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0039_auto_20200421_1921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pipelineexecutiontracking',
            name='old_participants',
        ),
    ]
