# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-04-28 16:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0040_remove_pipelineexecutiontracking_old_participants'),
    ]

    operations = [
        migrations.CreateModel(
            name='RedcapRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_id', models.CharField(max_length=50, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='database.Participant')),
            ],
        ),
    ]
