# Generated by Django 2.2.14 on 2020-10-08 21:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0040_fileastext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participantfcmhistory',
            name='token',
            field=models.CharField(db_index=True, max_length=256, unique=True, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
    ]
