# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-05-13 21:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0025_auto_20200106_2153'),
        ('database', '0041_redcaprecord'),
    ]

    operations = [
    ]
