# Generated by Django 2.2.14 on 2020-12-04 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0041_auto_20201008_2102'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='scheduledevent',
            unique_together=set(),
        ),
    ]
