# Generated by Django 2.2.14 on 2021-01-11 23:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0042_auto_20201204_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='intervention',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='intervention',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='interventiondate',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='interventiondate',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
