# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-05-09 03:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0042_auto_20200507_1511'),
        ('database', '0025_auto_20200106_2153'),
    ]

    operations = [
    ]
