# Generated by Django 2.2.14 on 2021-01-15 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0043_auto_20210111_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interventiondate',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
