# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-05-18 15:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0043_merge_20200509_0345'),
        ('database', '0042_merge_20200513_2117'),
    ]

    operations = [
    ]
