# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-05-18 15:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0044_merge_20200518_1506'),
    ]

    operations = [
        migrations.CreateModel(
            name='FitbitIntradayRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateTimeField()),
                ('activities_calories', models.FloatField(blank=True, null=True)),
                ('activities_steps', models.PositiveIntegerField(blank=True, null=True)),
                ('activities_distance', models.FloatField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Participant')),
            ],
        ),
        migrations.CreateModel(
            name='RedcapIntegration',
            fields=[
                ('study', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='database.Study')),
                ('server_url', models.CharField(max_length=2048)),
                ('api_token', models.CharField(max_length=256)),
            ],
        ),
        migrations.AddField(
            model_name='redcaprecord',
            name='study',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, to='database.Study'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='redcaprecord',
            name='record_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='redcaprecord',
            unique_together=set([('study', 'record_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='redcapintegration',
            unique_together=set([('server_url', 'api_token')]),
        ),
    ]
