# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-05-26 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0045_auto_20200518_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitbitintradayrecord',
            name='activities_heart',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
