# Generated by Django 2.2.15 on 2021-02-08 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0046_auto_20210128_1632'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='push_notification_unreachable',
        ),
        migrations.AddField(
            model_name='archivedevent',
            name='status',
            field=models.TextField(db_index=True, default='success'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='participant',
            name='push_notification_unreachable_count',
            field=models.SmallIntegerField(default=True),
        ),
        migrations.CreateModel(
            name='PushNotificationDisabledEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='database.Participant')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
