# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-06-17 18:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0046_fitbitintradayrecord_activities_heart'),
    ]

    operations = [
        migrations.CreateModel(
            name='FitbitInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('devices', models.TextField()),
                ('friends', models.TextField()),
                ('friends_leaderboard', models.TextField()),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Participant')),
            ],
        ),
        migrations.RenameField(
            model_name='fitbitcredentials',
            old_name='user',
            new_name='participant',
        ),
        migrations.RenameField(
            model_name='fitbitintradayrecord',
            old_name='last_updated',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='fitbitintradayrecord',
            old_name='user',
            new_name='participant',
        ),
        migrations.RenameField(
            model_name='fitbitrecord',
            old_name='last_updated',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='fitbitrecord',
            old_name='user',
            new_name='participant',
        ),
        migrations.AlterUniqueTogether(
            name='fitbitintradayrecord',
            unique_together=set([('participant', 'date')]),
        ),
        migrations.RemoveField(
            model_name='fitbitrecord',
            name='devices',
        ),
        migrations.RemoveField(
            model_name='fitbitrecord',
            name='friends',
        ),
        migrations.RemoveField(
            model_name='fitbitrecord',
            name='friends_leaderboard',
        ),
        migrations.AlterUniqueTogether(
            name='fitbitrecord',
            unique_together=set([('participant', 'date')]),
        ),
    ]
