# Generated by Django 2.2.14 on 2021-02-04 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0044_auto_20210121_0450'),
        ('database', '0046_auto_20210128_1632'),
    ]

    operations = [
    ]
