# Generated by Django 2.2.14 on 2021-03-22 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0049_auto_20210223_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='unregistered',
            field=models.BooleanField(default=False),
        ),
    ]
