# Generated by Django 2.2.19 on 2021-04-02 20:45
import json
import uuid

from django.db import migrations, models
import django.db.models.deletion


JASMINE_DEFAULTS = {
    "option": "daily",
    "tz_str": "America/New_York",
    "save_traj": False,  # intentionally left as a falsy value
}

WILLOW_DEFAULTS = {
    "option": "daily",
    "tz_str": "America/New_York",
}


def seed_forest_param(apps, schema_editor):
    """
    Seed initial default ForestParam objects
    """
    db_alias = schema_editor.connection.alias
    ForestParam = apps.get_model("database", "ForestParam")
    ForestParam.objects.using(db_alias).create(
        default=True,
        notes="The default parameters",
        name="default",
        jasmine_json_string=json.dumps(JASMINE_DEFAULTS),
        willow_json_string=json.dumps(WILLOW_DEFAULTS),
    )


def seed_study_forest_param(apps, schema_editor):
    """
    Add the default ForestParam to all existing studies
    """
    db_alias = schema_editor.connection.alias
    ForestParam = apps.get_model("database", "ForestParam")
    Study = apps.get_model("database", "Study")
    default_param = ForestParam.objects.get(default=True)
    Study.objects.using(db_alias).all().update(
        forest_param=default_param
    )


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0050_participant_unregistered'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ForestTracker',
        ),
        migrations.CreateModel(
            name='ForestParam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('default', models.NullBooleanField(unique=True)),
                ('notes', models.TextField(blank=True)),
                ('name', models.TextField(blank=True)),
                ('jasmine_json_string', models.TextField()),
                ('willow_json_string', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ForestTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('external_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('forest_tree', models.TextField(choices=[('jasmine', 'Jasmine'), ('willow', 'Willow')])),
                ('data_date_start', models.DateField()),
                ('data_date_end', models.DateField()),
                ('total_file_size', models.IntegerField(blank=True, null=True)),
                ('process_start_time', models.DateTimeField(blank=True, null=True)),
                ('process_download_end_time', models.DateField(blank=True, null=True)),
                ('process_end_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.TextField(choices=[('queued', 'Queued'), ('running', 'Running'), ('success', 'Success'), ('error', 'Error'), ('cancelled', 'Cancelled')])),
                ('stacktrace', models.TextField(blank=True, default=None, null=True)),
                ('forest_version', models.CharField(blank=True, max_length=10)),
                ('all_bv_set_s3_key', models.TextField(blank=True)),
                ('all_memory_dict_s3_key', models.TextField(blank=True)),
                ('forest_param', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='database.ForestParam')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='database.Participant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='summarystatisticdaily',
            name='study',
        ),
        migrations.AlterField(
            model_name='summarystatisticdaily',
            name='acceleration_direction',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='summarystatisticdaily',
            name='accelerometer_coverage_fraction',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='summarystatisticdaily',
            name='accelerometer_signal_variability',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='summarystatisticdaily',
            name='accelerometer_univariate_summaries',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='summarystatisticdaily',
            name='awake_onset_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='summarystatisticdaily',
            name='call_incoming_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='summarystatisticdaily',
            name='call_incoming_degree',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='summarystatisticdaily',
            name='call_incoming_duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='summarystatisticdaily',
            name='call_incoming_responsiveness',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='summarystatisticdaily',
            name='call_outgoing_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='summarystatisticdaily',
            name='call_outgoing_degree',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='summarystatisticdaily',
            name='call_outgoing_duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='summarystatisticdaily',
            name='device_proximity',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='summarystatisticdaily',
            name='distance_diameter',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='summarystatisticdaily',
            name='distance_from_home',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='summarystatisticdaily',
            name='distance_traveled',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='summarystatisticdaily',
            name='flight_distance_average',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='summarystatisticdaily',
            name='flight_distance_standard_deviation',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='summarystatisticdaily',
            name='flight_duration_average',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='summarystatisticdaily',
            name='flight_duration_standard_deviation',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='summarystatisticdaily',
            name='gps_data_missing_duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='summarystatisticdaily',
            name='home_duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='summarystatisticdaily',
            name='physical_circadian_rhythm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='summarystatisticdaily',
            name='physical_circadian_rhythm_stratified',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='summarystatisticdaily',
            name='radius_of_gyration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='summarystatisticdaily',
            name='significant_location_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='summarystatisticdaily',
            name='significant_location_entropy',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='summarystatisticdaily',
            name='sleep_duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='summarystatisticdaily',
            name='sleep_onset_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='summarystatisticdaily',
            name='stationary_fraction',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='summarystatisticdaily',
            name='text_incoming_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='summarystatisticdaily',
            name='text_incoming_degree',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='summarystatisticdaily',
            name='text_incoming_length',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='summarystatisticdaily',
            name='text_incoming_responsiveness',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='summarystatisticdaily',
            name='text_outgoing_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='summarystatisticdaily',
            name='text_outgoing_degree',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='summarystatisticdaily',
            name='text_outgoing_length',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='summarystatisticdaily',
            name='text_reciprocity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='summarystatisticdaily',
            name='total_power_events',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='summarystatisticdaily',
            name='total_screen_events',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='summarystatisticdaily',
            name='total_unlock_events',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='study',
            name='forest_param',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='database.ForestParam'),
        ),
        migrations.RunPython(seed_forest_param, migrations.RunPython.noop),
        migrations.RunPython(seed_study_forest_param, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='study',
            name='forest_param',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                                    to='database.ForestParam'),
        ),
        migrations.AddField(
            model_name='summarystatisticdaily',
            name='jasmine_tracker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='jasmine_summary_statistics', to='database.ForestParam'),
        ),
        migrations.AddField(
            model_name='summarystatisticdaily',
            name='willow_tracker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='willow_summary_statistics', to='database.ForestParam'),
        ),
    ]
