# Generated by Django 2.2.19 on 2021-04-02 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0051_forest_model_updates_20210402_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='foresttask',
            name='params_dict_cache',
            field=models.TextField(blank=True),
        ),
    ]
