# Generated by Django 2.2.19 on 2021-05-20 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0052_foresttask_params_dict_cache'),
    ]

    operations = [
        migrations.AddField(
            model_name='foresttask',
            name='forest_output_exists',
            field=models.NullBooleanField(),
        ),
    ]
