# Generated by Django 2.2.19 on 2021-05-20 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0053_foresttask_forest_output_exists'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foresttask',
            name='process_download_end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
